### ISSUE TITLE
Inconsistencies with gostatic.Page

### ISSUE THREAD

**Issue by mendelmaleh** [piranha/gostatic#100]
In the [README](https://github.com/piranha/gostatic#page-interface), it says:
> .Source - relative path to page source.
.FullSource - full path to page source.
.Path - relative path to page destination.
.FullPath - full path to page destination.

In practice, `FullSource()` doesn't exist, `FullPath()` returns the full path to source, not destination, and `OutputPath()` returns the full path to destination.
https://github.com/piranha/gostatic/blob/455a59d9bac1cb09e63f9cecd33bed1c62a5ec57/lib/page.go#L114-L120

This can be fixed in the readme or in the code itself, which makes more sense to me, but seems like there will be needed some renaming around (I guess this can be a breaking change).

**Comment by piranha** [comment]
Uhhh... that's embarassing. :)

Help is obviously nicer, but yeah, backward compatibility... maybe doing new vocabulary and then having current stuff work is the best way to approach this. I need to think about it.

If you have any suggestions, I'm all ears. :)

**Comment by mendelmaleh** [comment]
I guess having a new set of vocabulary is the safest option. On the other hand it would be cleaner not to keep backwards compatibility, so maybe postpone this to gostatic v3?
