### ISSUE TITLE
Html formating in site.gohtml can trigger <pre><code> output

### ISSUE THREAD

**Issue by cameronelliott** [piranha/gostatic#108]
Let me start by saying, I think this is likely my issue. :smile:

I have a block of HTML and template like so:
```
  <div class="container">
    <div class="posts">
      {{ range .Site.Pages.WithTag .Title }}
  <div class="post">
    <div><a href="{{ $.Rel .Url }}" class="title is-size-5">{{ .Title }}</a></div>
    <div class="subtitle is-6">{{ template "date" .Date }}</div>
  </div>
      {{ end }}
</div>
```

Depending upon how I format the indents,the output may or may not have ```<code><pre>``` blocks in the output. Just adding/dropping spaces can trigger this output.

Does anyone know why this is happening?
Thank you in advance.

**Comment by piranha** [comment]
I think it's markdown processing, because it parses 4 spaces before text as a code block!
