### ISSUE TITLE
Generate tag overview on 1 page

### ISSUE THREAD

**Issue by brenthuisman** [piranha/gostatic#111]
I'd like to have all pages broken out by tag, on one single page rather than separate pages.

I thought I'd loop over `{{ range .Site.Tags }}` but that gives `Error: Page blog.html: template: ad-hoc:16:18: executing "ad-hoc" at <.Site.Tags>: can't evaluate field Tags in type *gostatic.Site`. What is the right way to do this?

Second, how can I, in the loop, access the current tag (as string)?

I'm trying something like this
```
    {{ range .Site.Tags }}
    <h2>{{ "Tag" }}</h2>
    <ul>
      {{ range .Site.Pages.WithTag "Tag" }}
      <li>
        {{ template "date" .Date }} - <a href="{{ $.Rel .Url }}">{{ .Title }}</a>
      </li>
      {{ end }}
    </ul>
    {{ end }}
```

Thanks!

**Comment by piranha** [comment]
I started writing an answer here and realized that it's better to just create an example, [behold](https://github.com/piranha/gostatic/tree/master/examples)! :)

Please tell me if it's described enough, not sure if I need to add anything.

**Comment by brenthuisman** [comment]
Excellent! Didn't occur to me to loop over the virtual tag pages. Thanks!
