### ISSUE TITLE
# in <pre><code> missinterpreted

### ISSUE THREAD

**Issue by somenxavier** [piranha/gostatic#17]
If you put "#header" in "<pre><code>" block, then it is not interpreted as code, as:

<pre>
<code>
# header within code tag
</code>
</pre>

**Comment by somenxavier** [comment]
I think we should update this bug

**Comment by piranha** [comment]
Can't "repeat" their solution, to be honest. Adding 	`EXTENSION_LAX_HTML_BLOCKS` does nothing to the text you submitted...

**Comment by somenxavier** [comment]
So, can you update the [blackfriday issue](https://github.com/russross/blackfriday/issues/47).Two voices are heard more than once

**Comment by piranha** [comment]
Commented there. But how about using four spaces or triple backticks rather than tags to mark code?

```
\```
# hi
\```
```

Like that, but without backslashes. It works for me.

**Comment by somenxavier** [comment]
I don't know

**Comment by piranha** [comment]
What do you mean? :)

**Comment by somenxavier** [comment]
> Commented there. But how about using four spaces or triple backticks rather than tags to mark code?
I don't know

**Comment by piranha** [comment]
Well, replace `<pre><code>` and `</code></pre>` with three backticks each, and it should work properly.
