### ISSUE TITLE
Вопрос по шаблонам

### ISSUE THREAD

**Issue by Juev** [piranha/gostatic#23]
С параметрами, что задаются в шапке каждого файла вроде разобрался, доступ к ним осуществляется через `.Other` и последующим описанием параметра с большой буквы.

А каким образом можно получить информацию о предыдущей и следующей странице относительно текущей? Вижу в описании `.Prev` и `.Next`, параметры которые возвращают соответствующие страницы, но как можно получить так же и информацию по ним? К примеру, название и полный адрес этой страницы?

Понемногу разбираюсь, но думаю, еще не скоро во всем разберусь, так как в своем шаблоне страницы использую массу проверок и различных переменных:
https://github.com/Juev/juev.ru/blob/master/source/_layouts/default.html

**Comment by piranha** [comment]
Обманул немного, но теперь добавил всë, вроде. :)

**Comment by Juev** [comment]
Спасибо! :smile:
