### ISSUE TITLE
[FR] Permalink: опция для использования варианта Jekyll-ссылок

### ISSUE THREAD

**Issue by Juev** [piranha/gostatic#24]
GoStatic появился позже, чем Jekyll, в связи с чем многие имеют блоги именно на Jekyll. При попытке миграции с Jekyll на GoStatic приходиться переименовывать файлы со статьями, воссоздавая всю структуру, что ранее генерировалась автоматически движком.

К примеру, имя файла `2014-04-12-drafts.markdown` и при параметре `permalink:   pretty` в конфигурации Jekyll будет создана следующая структура:

```
- 2014
  |- 04
     |- 12
        |- drafts
           |- index.html
```

В gostatic для этого придется изначально создавать структуру:

```
- 2014
  |- 04
     |- 12
        |- drafts.md
```

Переименование файлов затратная по времени, тем более, если статей много. Плюс, подобную структуру директорий сложно поддерживать. Так как для того, чтобы изменить статью, придется переходить по всему дереву папок.

Почему бы не оставить вариант, что используется в gostatic сейчас, и добавить к нему опцию, с помощью которой можно было бы переключаться на вариант автоматической генерации структуры директорий, как в Jekyll. Одна опция для включения данной возможности, вторая опция для задания варианта структуры на основании имени файла.

Документация по возможным вариантам permalink в Jekyll доступна на странице:
http://jekyllrb.com/docs/permalinks/

**Comment by Juev** [comment]
any update?

**Comment by piranha** [comment]
Yeah, not really, PR welcome. :)
