### ISSUE TITLE
Add SafeHtml template function?

### ISSUE THREAD

**Issue by ottob** [piranha/gostatic#30]
I'm trying to add conditional comments for IE.

In hugo there is http://gohugo.io/templates/go-templates/#toc_9 and https://github.com/spf13/hugo/blob/master/tpl/template.go#L919

Would you mind adding something similar to gostatic?

**Comment by piranha** [comment]
I use `text/template` rather than `html/template`, so it shouldn't escape them anyway. Does it?

**Comment by ottob** [comment]
You are correct. I should have tested it first.
