### ISSUE TITLE
Support templates folder?

### ISSUE THREAD

**Issue by ottob** [piranha/gostatic#31]
I'm creating a lot of templates so the TEMPLATES line of `config` is getting rather long. It would be nice if you could specify a folder `TEMPLATES = templates/` (or something similar) and that all templates of that folder would be parsed.

Something like this seems to work (config.go:110):
```go
	case "TEMPLATES":
		templates := strings.Split(bits[1], " ")
		for _, template := range templates {
			if strings.HasSuffix(template, "/") {
				files, _ := filepath.Glob(template + "*.tmpl")
				for _, file := range files {
					cfg.Templates = append(cfg.Templates, filepath.Join(base, file))
				}
				continue
			}
			cfg.Templates = append(cfg.Templates, filepath.Join(base, template))
		}
	case "SOURCE":
```

**Comment by piranha** [comment]
See https://github.com/piranha/gostatic/releases/tag/1.15 :)

**Comment by ottob** [comment]
Thanks!
