### ISSUE TITLE
Update fsnotify?

### ISSUE THREAD

**Issue by ottob** [piranha/gostatic#32]
The project is now maintained at gopkg.in/fsnotify.v1 and there has been some fixes committed lately.

See https://groups.google.com/d/msg/golang-nuts/LCKzZLfUneQ/d5GiWT6O6xQJ

**Comment by piranha** [comment]
That seemed like a good idea, plus was easy to do, so [here](https://github.com/piranha/gostatic/releases/tag/1.16) we go.

**Comment by ottob** [comment]
Thanks, but I think there might be an issue with your update:
Shouldn't `if ev.Op == fsnotify.Create {` and `if ev.Op == fsnotify.Remove {`
instead be: `if ev.Op&&fsnotify.Create == fsnotify.Create {` and `if ev.Op&fsnotify.Remove == fsnotify.Remove {` ?

Since ev.Op is now a bitfield. See for instance https://github.com/revel/revel/commit/065c84c1d414df42755812ded6ce95cc3ebbf506 and http://godoc.org/gopkg.in/fsnotify.v1#ex-NewWatcher

**Comment by piranha** [comment]
Heh, you are right, 1.17 is out. :)
