### ISSUE TITLE
Gostatic as library

### ISSUE THREAD

**Issue by zhuharev** [piranha/gostatic#36]
What do you think about how to rewrite the code as library, like [this](/zhuharev/gostatic)?

This will facilitate the development of modules and control systems.

**Comment by piranha** [comment]
I actually like the idea. :) It seems there are no downsides, and yeah, it'll be possible to extend for weird use-cases.

The only problem is that I never carefully thought about what's exposed and what's not, plus my documentation habits could be better, so there is that, but I guess that can be improved bit by bit in a future...

**Comment by piranha** [comment]
Hey, so I mean, pull requests are welcome. :-)

**Comment by zhuharev** [comment]
@piranha wait until the weekend, i need some refactoring
