### ISSUE TITLE
Relativize results in blank href for pages under root linking to /

### ISSUE THREAD

**Issue by holic** [piranha/gostatic#38]
I have a structure like:

```
src/
  index.html
  preview.html
```

`preview.html` links to the site index via `<a href="/">` and I'm using `relativize` to make all links relative. However, the resulting link ends up as `<a href="">` when I would expect something like `<a href=".">`.

**Comment by piranha** [comment]
Hm, not exactly sure how to reproduce that - I guess `Page.Rel()` should just check if it tries to return an empty string, then it should return a dot?

**Comment by holic** [comment]
That should do it. Or consider prepending all relative URLs with `./`.

**Comment by piranha** [comment]
Should return a dot now. Please reopen if not. :)

**Comment by holic** [comment]
Still seeing an empty `href`.

**Comment by piranha** [comment]
I can't reproduce this issue, to be honest. Can you maybe create a small case showing the problem?

**Comment by holic** [comment]
Yep, sure. Shall I submit a PR for it? Or just create a new repo you can check out?

**Comment by piranha** [comment]
PR would be wonderful! So that the case is in for the future. :)
