### ISSUE TITLE
Include template changes when determining which pages to re-render

### ISSUE THREAD

**Issue by holic** [piranha/gostatic#39]
Is it possible that the re-rendering of only changed files can include template changes as well? And any pages using those templates?

For example, if I change `archive.tmpl`, then all the pages using that template should be re-rendered on `gostatic config`.

Gostatic is already blazing fast (~4 seconds for a full render instead of ~2 minutes with Jekyll), but just curious if it can be even smarter about what it chooses to re-render. :)

**Comment by piranha** [comment]
That one is a bit hard, haha. I have thought about that, but got no good idea. Maybe it should collect templates from processor rules and then check template modification dates... But then I don't think it's easier to understand what file the template comes from.

Other possibility is to consider template files as a dependency for every file. :-)

**Comment by piranha** [comment]
Also, I'm happy to learn about your timings! :-)

**Comment by piranha** [comment]
Done by a06d526
