### ISSUE TITLE
Support arrays/slices in `truncate` function

### ISSUE THREAD

**Issue by holic** [piranha/gostatic#41]
e.g. `PageSlice` so we can do things like:

```
{{ range (truncate 10 .Site.Pages) }}
  {{ .Content }}
{{ end }}
```

**Comment by holic** [comment]
In Go templates, do pipelined function calls use the value to the left of the pipe as the last argument in the function call? e.g.

```
{{ range .Site.Pages | truncate 10 }}
  {{ .Content }}
{{ end }}
```

**Comment by piranha** [comment]
Unfortunately Go's type system won't let me do that nicely. Ehm... I could make `truncate` get an `interface{}` and then dispatch, but that will slow down this function a bit, plus drop a bit of type safety (thought templates are not exactly type safe anyway).

Another option is adding a method to PageSlice, `.Slice` or something along the lines.

And yes, you can pipeline exactly like that. But I messed up few functions (`replace`, for example) at some point where I forgot about that. :\ And now I'm not sure how to proceed. :)

**Comment by holic** [comment]
`.Slice` would work, especially if it accepted a limit/length and offset/start index.

Not sure how Go does versioning (esp. for breaking changes), but I'd personally rather see `replace`, etc. fixed to be more useful in pipelines than leave em laying around.

**Comment by piranha** [comment]
If you're doing `go get`, then there is no real versioning. But I do release versions myself and I could cut out 2.0 just to break backward compatibility, of course.

**Comment by piranha** [comment]
[It](https://github.com/piranha/gostatic/commit/8132da9c05f652a01f323d2707c122222f97ce98) was there for a long time. :-)

**Comment by holic** [comment]
:+1:
