### ISSUE TITLE
Lock down dependencies

### ISSUE THREAD

**Issue by holic** [piranha/gostatic#45]
I'm not sure how best to do this in the Go universe (I've seen https://github.com/tools/godep), but it would be great to lock down external dependencies to a specific version/revision so that site builds are entirely reproducible. I'm seeing some differences between sites generated on a server with a fresh install of gostatic vs. my local copy.

Thoughts?

**Comment by piranha** [comment]
I'd like that, but I really have no idea what's the best way to do that right now. :) Contributions are welcome!

**Comment by krpors** [comment]
Go 1.5 has experimental vendoring. I might take a look soon to see if I can get something to work. I'm new to this vendoring anyway, so probably a good exercise.
