### ISSUE TITLE
minor bug in blog.atom in example template

### ISSUE THREAD

**Issue by somenxavier** [piranha/gostatic#48]
Hi,

in `blog.atom`, generated by `gostatic -i`, please change:
```
  <link href="{{ .Site.Other.Url }}{{ .Url }}" rel="alternate"></link>
```
with
```
  <link href="{{ .Site.Other.Url }}/{{ .Url }}" rel="alternate"></link>
```
because usually the site is typed without final trail slash (like google.com and not google.com/). Perhaps you could improve that with an if...

Thanks,

**Comment by piranha** [comment]
It's in 2.2 :-)

**Comment by somenxavier** [comment]
thanks

**Comment by somenxavier** [comment]
Perhaps it could be improved with an `if`: `if the url have slash and the end....`

**Comment by piranha** [comment]
Yeah... I'll think about that.
