### ISSUE TITLE
[question] How can I build a glossary?

### ISSUE THREAD

**Issue by somenxavier** [piranha/gostatic#49]
Hi,

How can I make a list of all tags and the associated pages (like [this](http://somenxavier.github.io/cepasud/tags.html))?

Thanks a lot,

**Comment by piranha** [comment]
List of tags: https://github.com/piranha/solovyov.net/blob/master/src/tags/index.html
List of pages inside a tag: https://github.com/piranha/solovyov.net/blob/master/site.tmpl#L102-L104

**Comment by somenxavier** [comment]
Thanks. Perhaps you could put it as an example in the Wiki?

**Comment by somenxavier** [comment]
How can I count that? How can I count the number of pages with one tag? I can't find it in the "API"

**Comment by piranha** [comment]
What do you mean by 'count'? Like, a count of tags you have on the site?

**Comment by somenxavier** [comment]
I mean count the number of pages with have this specific tag

**Comment by piranha** [comment]
Ah! [Here](https://github.com/piranha/gostatic#page-list-interface) is description of `.Len` method. You can use it like that:

```
{{ with .Site.Pages.WithTag .Title }}{{ .Len }}{{ end }}
```

Unfortunately, I don't know a clearer/shorter way, but [see here](https://github.com/piranha/gostatic/blob/master/test/template.tmpl#L57-L63) an example.

**Comment by piranha** [comment]
Added this stuff to the [wiki](https://github.com/piranha/gostatic/wiki). :)

**Comment by somenxavier** [comment]
Thanks a lot. Now more clear.
