### ISSUE TITLE
Please put .Exec as available functions in  templating functions

### ISSUE THREAD

**Issue by somenxavier** [piranha/gostatic#51]
In [templating](https://github.com/piranha/gostatic#templating), you put a lot of functions. Can you please put `.Exec`. For running this:

```
{{.Exec "/bin/bash" "-c" "git log --pretty=oneline | wc -l "}}
```

**Comment by piranha** [comment]
That make sense, I could do that!

**Comment by somenxavier** [comment]
tnks
