### ISSUE TITLE
File with CRLF + markdown renderered incorrectly

### ISSUE THREAD

**Issue by krpors** [piranha/gostatic#57]
In before this gets lost from my memory: source pages which are in markdown format, with some front matter, are rendered incorrectly when their EOL is set to CRLF. To reproduce:

1. Run `gostatic -i bughunt`
1. Change `bughunt/src/index.html` to have CRLF line endings
1. Run `gostatic bughunt/config`
1. Observe `bughunt/site/index.html`.

LF version (correct):

    <title>Example Site: Main Page</title>
    ...
	<body>

	  <ul class="post-list">

	  <li>

CRLF version (incorrect):

    <title>Example Site</title>
    ....
    <body>

      title: Main Page
    ----
    <ul class="post-list">

      <li>

**Comment by piranha** [comment]
Oh, I think that's because `config` splits on `----\n`, and CRLF has `----\r\n` instead. Maybe we should just split by regexp there? Like, `----\r?\n`.

**Comment by krpors** [comment]
Indeed, [see source](https://github.com/piranha/gostatic/blob/master/processors/config.go#L27). I guess the safest version would be to use a Scanner to read line by line until the `----` has been found. See the [example](https://golang.org/pkg/bufio/#example_Scanner_lines) from the bufio package.

**Comment by piranha** [comment]
I was also thinking - maybe try to split by `\n----\n`, and if it didn't work (there is only one part), then try to split by `\r\n----\r\n`. 

Or even better! Choose splitter based on whenever there is `\r` contained in the file or not and if somebody *mixes* various line endings, that's their problems. :)

**Comment by krpors** [comment]
Well that doesn't sound too user friendly... :P I'll check if I can whip something up with a reader or whatever. That way it doesn't really matter if you use \r\n, or \n, or \r or whatever the editor/user makes of it.

**Comment by LaBetonneuse** [comment]
Hi, I got the notice and I'll test that later (not sure when, though, I'm very busy at the moment).
I've read the comments and I'm pretty sure some systems use \r as the EOL marker so shouldn't we (i.e. you ;) ) cover all combinations (CRLF, CR and LF) ? What do you think?
Aren't there native Go functions that deal with that ?

**Comment by krpors** [comment]
There was some merit in your comment. I remember MacOS used CR exlusively, but after some research, this only seem to apply to version prior MacOS X or whatever. Check out [this list](https://en.wikipedia.org/wiki/Newline#Representations), and [here](http://superuser.com/questions/439440/did-mac-os-lion-switch-to-using-line-feeds-lf-n-for-line-breaks-instead-of). 

AFAIK, gostatic (or any other Go program) doesn't compile on the other systems mentioned (Acorn BBC, QNX, RISC ...), so I suppose Windows `CRLF` and the Nix-es + Macs `LF` remain to support.

**Comment by LaBetonneuse** [comment]
At least we've learnt something in the process. ;)
I tried both 32 and 64 bit editions of the latest version and neither worked (both on Win8 x64).

**Comment by krpors** [comment]
Did you use the binary that was built from source? If you didn't, that explains why neither worked :) The fix has been introduced in commit [311e9e5](https://github.com/piranha/gostatic/commit/311e9e5f9f7383e3f1a5b6304a5f0f6a4ad137a5).

**Comment by LaBetonneuse** [comment]
I went to the download page without a second look. ^^
Is there a binary with the fix lying around?

**Comment by LaBetonneuse** [comment]
I downloaded the tools and the source code but I haven't used a Makefile in a while and I'm running Windows anyway. I don't have the time to figure out how to build it at the moment, is there a "how to build GoStatic on MS Windows(R) for dummies" doc, by any chance?

**Comment by piranha** [comment]
Let's do it other way around: I'll just check a bit later myself and will do a new release if it works. :)

**Comment by piranha** [comment]
Ok, I've checked and it works, so you can download 2.4, which will work. :)

**Comment by LaBetonneuse** [comment]
It does indeed. Thanks. :)
