### ISSUE TITLE
[support] how to get the "image" of the post

### ISSUE THREAD

**Issue by somenxavier** [piranha/gostatic#62]
Hi,

I would like to put `image: yes` in the YAML header of my post, and that gostatic knows that the image associated to the post `foo.md` is `foo.jpeg`. How can I achieve that?

**Comment by piranha** [comment]
You can check for custom values in header with `{{ .Other.Image }}` - see description of what you get in `Page` context [here](https://github.com/piranha/gostatic#page-interface).

**Comment by somenxavier** [comment]
Thanks. How can I process it?

(in pseudocode)
```
if .Other.Image then
  {{ .Other.Image }}
```

How is that in go?

**Comment by piranha** [comment]
`{{ if .Other.Image }} {{ .Other.Image }} {{ end }}` should be good enough...

**Comment by somenxavier** [comment]
Thanks a lot,
