### ISSUE TITLE
[support] Sorting tags

### ISSUE THREAD

**Issue by somenxavier** [piranha/gostatic#63]
Hi,

I have this:
```
<div class="tag-list">
<ul class="glossari">
{{ range .Site.Pages.Children "tags/" }}
  {{ if .Title }}
    <li> <a href="{{ $.Rel .Url }}">{{ .Title }}</a> ({{ with .Site.Pages.WithTag .Title }}{{ .Len }}{{ end }})</li>
  {{ end }}
{{ end }}
</ul>
</div>
```
and I want to sort `.Site.Pages.Children "tags/" ` alphabetically

**Comment by piranha** [comment]
That's something not really supported now, but I like the idea. Something needs to be done about that. :-)

**Comment by somenxavier** [comment]
A pitty. Please, put it as "client request" ;-)

**Comment by somenxavier** [comment]
The tags also could be sorted by number of pages which have each tag (for making tag cloud)

**Comment by piranha** [comment]
So yeah, instead of doing some sorting stuff I went the lazy way and if pages have same Date they are sorted by name now. Should be enough for your use case. :)

**Comment by somenxavier** [comment]
My case is [this](https://github.com/piranha/gostatic/issues/63#issue-121468021), which gives me [this](http://somenxavier.xyz/tags/). I prefer sorting *always* tags in alphabetical order

**Comment by piranha** [comment]
Interesting. That's with gostatic 2.6? Sorry I didn't mention this earlier. :)

**Comment by somenxavier** [comment]
I don't understand you. Sorting with (date, name) is not the same as sorting just with name. I think that in the majority of cases, you have a few pages with the same date.

**Comment by piranha** [comment]
Tag pages are virtual pages and they all have [same date](https://github.com/piranha/gostatic/blob/master/processors/tags.go#L61), that's why this works for them.

This is how tags page looked for me before change: https://monosnap.com/file/RieVtzNyusxBFUmZO7yKkIfXaIok3w
And this is after: https://monosnap.com/file/LyxzCXUxxMl4SGDF6AcrXFR7yVvlrv

**Comment by somenxavier** [comment]
Many thanks, and much better explanation. This is exactly what I wanted.
