### ISSUE TITLE
UTF-8 with BOM support

### ISSUE THREAD

**Issue by LaBetonneuse** [piranha/gostatic#79]
Hello !

I started working on a new website and couldn't figure out why the page's titles weren't available when rendering the pages.
My hunch was that somehow the beginning of the first line (where the title is) wasn't read properly so the title was ignored and, after a quick investigation, I realised that my files were indeed saved as UTF-8 with BOM which would explain it. Switching to UTF-8 without BOM solved the problem.
Is it a bug or a "feature" ? ;)

Thanks.

**Comment by piranha** [comment]
I guess it's more of a bug than a feature. :-) I'd be willing to accept a fix for that!

**Comment by piranha** [comment]
Fixed in #89 :-)
