### ISSUE TITLE
Question: how to you relativize paths?

### ISSUE THREAD

**Issue by somenxavier** [piranha/gostatic#82]
Hi,

In one document I use 
```
[![](/static/files/foo.jpeg)](/static/files/foo.jpeg)
```
How gostatic knows that `/static` is about `/site/static/` and not really `/static/` in my drive?

**Comment by piranha** [comment]
If you add `inner-template` processor in your config for a page like that, you can do this:

```
[![]({{ $.Rel "/static/files/foo.jpeg" }})]({{ $.Rel "/static/files/foo.jpeg" }})
```

this will generate url which is relative to the location of the current page, something like `../../static/files/foo.jpeg`. I'm not exactly sure how to do that automatically. :)

**Comment by somenxavier** [comment]
Thanks
