### ISSUE TITLE
Large memory usage when downloading large files

### ISSUE THREAD

**Issue by Danielv123** [piranha/gostatic#84]
Every time a download of a large file is initiated (~800 mb) goStatic consumes large amounts of ram for a while.

Every time a request is initiated shows up as red in the top graph. The bottom graph is container memory usage in a range of 0 - 1 GB.

![Image](https://i.imgur.com/OWb5elG.png)

**Comment by piranha** [comment]
Hm, interesting! How do you download a file with gostatic?

**Comment by Danielv123** [comment]
I have a  folder on my site called "archive", where I store large zips of data. Navigating to the URL gives me a nice interface by default for downloading files, much like how FTP is handled.

**Comment by piranha** [comment]
Okay, but how is gostatic involved in that?

**Comment by Danielv123** [comment]
You must have missunderstood what I said. The entire server side part of the download is handled by gostatic. The purple line in the graph above is the memory usage of my gostatic docker container, not FTP or other services. This leads me to think that gostatic is handling something weird, like reading the entire file into memory.

To reproduce:

run ``sudo docker run -d -p 1935:8043 -v /srv/goStatic:/srv/http --name goStatic pierrezemb/gostatic```

Place large zip file in ``/srv/goStatic``

Navigate to localhost:1935/largeFile.zip

Observe memory usage.

**Comment by piranha** [comment]
I think you are looking for https://github.com/PierreZ/goStatic :-)

**Comment by Danielv123** [comment]
Whoops, my mistake!
