### ISSUE TITLE
dump option

### ISSUE THREAD

**Issue by rafaelespinoza** [piranha/gostatic#97]
How is the `--dump` (or `-d`) option supposed to work? The usage function says

> -d, --dump=    print page metadata as JSON (pass path to source or target file)

So, I'll try `gostatic -d src/index.html` or `gostatic -d src/blog/first.md`. This results in showing the usage function and a non-zero exit code.

Is this an obsolete option or am I using it incorrectly?

**Comment by piranha** [comment]
You have to do `gostatic -d index.html config` - path to config is required, and path to file should be relative to target/source directory. I'll fix help string. :)
