### ISSUE TITLE
download script

### ISSUE THREAD

**Issue by tcurdt** [piranha/gostatic#99]
I'd suggest updating the download script in the README to something more along the lines of

```
PLATFORM=linux # mac or win
URL=`curl -s https://api.github.com/repos/piranha/gostatic/releases | awk '/download_url.*64-'$PLATFORM'/ { gsub(/"/, "", $2); print $2; exit }'`
curl -sL $URL -o gostatic
chmod a+x gostatic
```

The call to `curl` was missing a follow redirects and it seems to need a `chmod`. Also the `URL` should not have quotes.

At least on mac it works that way.

**Comment by piranha** [comment]
Thanks!
